## -----------------------------------------------
## Basic Configuration
## -----------------------------------------------

languageCode = 'en-us'
title = 'Jackson Gothe-Snape'

## -----------------------------------------------
## Publish
## -----------------------------------------------

#relativeURLs = "true"
#canonifyURLs = "true"

# Local
#baseURL = "/"
publishDir = "public"

# Remote
baseURL = "https://jacksongs.github.io/gothesnape"
#publishDir = "//centos/sites/hugodev/hugostory/"


## -----------------------------------------------
## Hugo Built-in Features
## -----------------------------------------------

disableKinds = ["taxonomy", "taxonomyTerm", "section"]
# googleAnalytics = "your-google-analytics-id"

## -----------------------------------------------
## Site Parameters
## -----------------------------------------------

[Params]

[Params.social]
twitter = "https://www.twitter.com/jacksongs"
github = "https://www.github.com/jacksongs"
instagram = "https://www.instagram.com/jacksongs"
linkedin = "https://www.linkedin.com/in/jacksongs/"
email = "jack.snape@theguardian.com"